export { 
    BLOCK_INFO_CONTACTS, 
    BLOCK_INFO_DEFAULT, 
    BLOCK_INFO_GALLERY, 
    CAROUSEL_INFO_CAR, 
    INTERACTION_CAR,
    MENU_ITEM, 
    REGISTER,
    COMMENTS,
    SIGN_IN,
    PROFILE,
    BUTTON,
    LOTTERY,
} from './Text'